package data;
// Generated Nov 20, 2014 9:23:46 PM by Hibernate Tools 4.3.1



/**
 * Language generated by hbm2java
 */
public class Language  implements java.io.Serializable {


     private int languageId;
     private String name;

    public Language() {
    }

	
    public Language(int languageId) {
        this.languageId = languageId;
    }
    public Language(int languageId, String name) {
       this.languageId = languageId;
       this.name = name;
    }
   
    public int getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(int languageId) {
        this.languageId = languageId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


