package data;
// Generated Nov 20, 2014 9:23:46 PM by Hibernate Tools 4.3.1



/**
 * LiveCountry generated by hbm2java
 */
public class LiveCountry  implements java.io.Serializable {


     private LiveCountryId id;

    public LiveCountry() {
    }

    public LiveCountry(LiveCountryId id) {
       this.id = id;
    }
   
    public LiveCountryId getId() {
        return this.id;
    }
    
    public void setId(LiveCountryId id) {
        this.id = id;
    }




}


