package data;
// Generated Nov 20, 2014 9:23:46 PM by Hibernate Tools 4.3.1



/**
 * LiveCountryId generated by hbm2java
 */
public class LiveCountryId  implements java.io.Serializable {


     private int userId;
     private int countryId;

    public LiveCountryId() {
    }

    public LiveCountryId(int userId, int countryId) {
       this.userId = userId;
       this.countryId = countryId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LiveCountryId) ) return false;
		 LiveCountryId castOther = ( LiveCountryId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getCountryId()==castOther.getCountryId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getCountryId();
         return result;
   }   


}


