package data;
// Generated Nov 20, 2014 9:23:46 PM by Hibernate Tools 4.3.1



/**
 * ShareVideo generated by hbm2java
 */
public class ShareVideo  implements java.io.Serializable {


     private ShareVideoId id;

    public ShareVideo() {
    }

    public ShareVideo(ShareVideoId id) {
       this.id = id;
    }
   
    public ShareVideoId getId() {
        return this.id;
    }
    
    public void setId(ShareVideoId id) {
        this.id = id;
    }




}


