package data;
// Generated Nov 20, 2014 9:23:46 PM by Hibernate Tools 4.3.1



/**
 * SpeakLanguageId generated by hbm2java
 */
public class SpeakLanguageId  implements java.io.Serializable {


     private int userId;
     private int languageId;

    public SpeakLanguageId() {
    }

    public SpeakLanguageId(int userId, int languageId) {
       this.userId = userId;
       this.languageId = languageId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(int languageId) {
        this.languageId = languageId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SpeakLanguageId) ) return false;
		 SpeakLanguageId castOther = ( SpeakLanguageId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getLanguageId()==castOther.getLanguageId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getLanguageId();
         return result;
   }   


}


