package data;
// Generated Nov 20, 2014 9:23:46 PM by Hibernate Tools 4.3.1



/**
 * SpeakLanguage generated by hbm2java
 */
public class SpeakLanguage  implements java.io.Serializable {


     private SpeakLanguageId id;

    public SpeakLanguage() {
    }

    public SpeakLanguage(SpeakLanguageId id) {
       this.id = id;
    }
   
    public SpeakLanguageId getId() {
        return this.id;
    }
    
    public void setId(SpeakLanguageId id) {
        this.id = id;
    }




}


