package data;
// Generated Nov 20, 2014 9:23:46 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userId;
     private String firstName;
     private String lastName;
     private String username;
     private String password;
     private Boolean shareVideo;

    public User() {
    }

	
    public User(int userId) {
        this.userId = userId;
    }
    public User(int userId, String firstName, String lastName, String username, String password, Boolean shareVideo) {
       this.userId = userId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.username = username;
       this.password = password;
       this.shareVideo = shareVideo;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getShareVideo() {
        return this.shareVideo;
    }
    
    public void setShareVideo(Boolean shareVideo) {
        this.shareVideo = shareVideo;
    }




}


