package data;
// Generated Nov 20, 2014 9:23:46 PM by Hibernate Tools 4.3.1



/**
 * WatchedVideo generated by hbm2java
 */
public class WatchedVideo  implements java.io.Serializable {


     private WatchedVideoId id;

    public WatchedVideo() {
    }

    public WatchedVideo(WatchedVideoId id) {
       this.id = id;
    }
   
    public WatchedVideoId getId() {
        return this.id;
    }
    
    public void setId(WatchedVideoId id) {
        this.id = id;
    }




}


